# chenge some software's default modle
alias vi='vim'
alias vimtutor='vimtutor zh_CN'
alias mit='mit-scheme'
alias more='less'
alias wirte-good='npx write-good'
alias start='xdg-open'

# some personal aliases
alias fd='fdfind'
alias cls='clear'
alias aptupdl='sudo apt update && echo "执行 apt list --upgradable" && apt list --upgradable'
alias rmexe='find . -name "*.exe" -type f -delete'
alias rmout='find . -name "*.out" -type f -delete'
alias rmeditorbackup='find . -name "*~" -type f -delete && find . -name ".*.swp" -type f -delete'
alias rmzoneinent='find . -name "*:Zone.Identifier" -type f -delete'
alias codew='code $WORKING'
alias workw='cd $WORKING && code .'
alias codebashrc='code ~/.bashrc'
alias codealiases='code ~/.bash_aliases'
alias bochs='~/bochs/bin/bochs'
alias sbochs='sudo ~/bochs/bin/bochs'
alias emacsnw='emacs -nw'
alias py3doctest='python3 -m doctest'
alias ok='python3 ok --local'

# some personal cd aliases
alias cdw='cd $WORKING'
alias cdmycode='cd ~/code/mycode/'
alias cdccode='cd /mnt/c/Users/wangl/code'

# some personal git aliases
alias gs='git status'
alias gaa='git add .'
alias gc='git commit'
alias gcm='git commit -m'
alias gcam='git commit -am'
alias gist='gitstart'
alias gifi='gitfinish'
alias gitstart='git checkout master && git pull && git checkout doing && git merge master'
alias gitfinish='git checkout master && git merge doing && git push && git checkout doing'
alias glog='git log --graph --all --decorate'
alias gitlog='git log --graph | less'
